spring:
  application:
    name: notes
  security:
    user:
      name: user

      password: user1


  datasource:
    url: jdbc:mysql://localhost:3306/securenotes
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true


logging:
  level:
    root: INFO              # general log level
    org.springframework: INFO
    org.hibernate.SQL: DEBUG       # logs executed SQL
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # logs parameter values